# Generated by Django 3.0.4 on 2020-03-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_sy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.CharField(blank=True, default='static/manage_sy/profilepics/profile_avatar_contact_account_user_default-neutral.png', max_length=100),
        ),
    ]
