# Generated by Django 3.0.4 on 2020-03-15 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_sy', '0002_member_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSubTypeDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('R', 'Request For'), ('C', 'Confess It')], max_length=10, null=True)),
                ('subType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=500)),
                ('assigned_to', models.CharField(default=' ', max_length=100)),
                ('type', models.CharField(blank=True, choices=[('R', 'Request For'), ('C', 'Confess It')], max_length=10, null=True)),
                ('happened_on', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, choices=[('R', 'Request For'), ('C', 'Confess It')], max_length=10, null=True)),
                ('active', models.BooleanField(default=False)),
                ('image_clue', models.CharField(blank=True, default='static/manage_sy/profilepics/profile_avatar_contact_account_user_default-neutral.png', max_length=1000)),
                ('notes', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_types', to='manage_sy.ItemSubTypeDomain')),
            ],
        ),
    ]
