# Generated by Django 3.0.4 on 2020-03-16 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_sy', '0003_itemsubtypedomain_syitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='companion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='companion_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='home_name',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_first_registered',
            field=models.BooleanField(default=True),
        ),
    ]
