# Generated by Django 3.0.4 on 2020-03-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_sy', '0004_auto_20200316_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='syitem',
            name='response_type',
            field=models.CharField(blank=True, choices=[('Y', 'Accepted'), ('N', 'Rejected')], max_length=10, null=True),
        ),
    ]
