# Generated by Django 3.0.4 on 2020-03-20 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_sy', '0005_syitem_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='syitem',
            name='response_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
