# Generated by Django 3.0.4 on 2020-03-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_sy', '0006_syitem_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syitem',
            name='response_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
